#JWT Secret
app.secret: Prasad

server:
  port: 8080

user:
  db:
    host: localhost
    port: 3306
    name: mydb
    username: root
    password: password

spring:
  datasource:
    url: jdbc:mysql://${user.db.host}:${user.db.port}/${user.db.name}
    username:  ${user.db.username}
    password:  ${user.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
  application:
    name: user-service-security
